<?php
/* @var $this Win\Mvc\Block */
/* @var $user Win\Authentication\User */
?>
Olá, <b><?= $user->getName(); ?></b>.<br />
<b>Você solicitou a redefinição de sua senha no site: <?= $this->app->getName(); ?>.</b>
<br /><br />

Para definir uma nova senha clique no link abaixo:<br />

<b><?= $this->app->getBaseUrl(); ?>login/alterar-senha/<?= $user->getRecoreryHash(); ?>/</b>

<br /><br />
Se o link acima não funcionar, copie e cole em seu navegador.<br />
Se você não solicitou a redefinição de senha, apenas ignore esta mensagem.