<?php

use Win\Authentication\RecoveryPassword;
use Win\Authentication\User;
use Win\Mvc\Block;

/* @var $this Block */
/* @var $user User */
?>
Olá, <b><?= $user->name; ?></b>.<br />
<b>Você solicitou a redefinição de sua senha no site: <?= $this->app->getName(); ?>.</b>
<br /><br />

Para definir uma nova senha clique no link abaixo:<br />

<a href="<?= RecoveryPassword::getUrl($user); ?>">
	<b><?= RecoveryPassword::getUrl($user); ?></b>
</a>

<br /><br />
Se o link acima não funcionar, copie e cole em seu navegador.<br />
Se você não solicitou a redefinição de senha, apenas ignore esta mensagem.