<?php

use Win\Templates\Template;
use Win\Common\Utils\Link;
use Win\Common\Utils\Str;
use Win\Services\Router;

/** @var Template $this */
/** @var string $content */
$router = Router::instance();
$bodyClass = $router->page . '-' .  Str::toUrl($router->action);
?>
<!DOCTYPE html>
<html lang="pt-BR">
<?= new Template('layout/head'); ?>

<body class="<?= $bodyClass; ?>">
	<header>
		<nav class="main-nav">
			<a id="logo" href="<?= $router->baseUrl; ?>">
				<img src="public/img/win.svg" alt="<?= APP_NAME; ?>" />
			</a>
			<input type="checkbox" id="menu-toggle" />
			<label for="menu-toggle"></label>
			<ul>
				<li>
					<a href="./" class="<?= Link::active('index'); ?>">Página Inicial</a>
				</li>
				<li>
					<a href="demo" class="<?= Link::active('exemplo'); ?>">Exemplo</a>
				</li>
				<li>
					<a href="contato" class="<?= Link::active('contato'); ?>">Contato</a>
				</li>
				<li>
					<a href="nao-existe">404</a>
				</li>
			</ul>
		</nav>
	</header>

	<div class="middle">
		<?= $content; ?>
		<br />
	</div>

	<footer>
		Made with <span class="heart"></span> by
		<a href="https://github.com/winframework/winphp" target="_blank">
			<?= APP_NAME; ?>
		</a>
		&copy; <?= date('Y'); ?>
	</footer>
</body>

</html>