<?php /* @var $this Win\Mvc\Block */ ?>
<head>
	<base href="<?php echo $this->app->getBaseUrl(); ?>" />
	<title><?php echo $this->app->view->getTitle(); ?></title>

	<!-- Meta Tags -->
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<!-- Demo Files -->
	<link rel="stylesheet" href="public/css/styles.css" />
	<link rel="stylesheet" href="public/css/styles1.css" />
	<link rel="shortcut icon" type="image/x-icon" href="public/img/favicon.ico" />

</head>