<?php

use Win\Views\View;

/** @var View $this */
?>
<main>
	<h1>Exemplos Básicos</h1>

	<ul>
		<li><a href="basic">Básico</a></li>
		<li><a href="basic-class">Class</a></li>
		<li><a href="alternative-layout">Layout Alternativo</a></li>
		<li><a href="return-five">Return 5</a></li>
		<li><a href="namespace">Namespace</a></li>
		<li><a href="json-api">Json API</a></li>
		<li><a href="alerts">Alert</a></li>
		<li><a href="redirecting">Redirecionador</a></li>
		<li><a href="private">Método Privado (Erro)</a></li>
	</ul>

	<h1>404</h1>
	<ul>
		<li><a href="rota404">Rota Not found</a></li>
		<li><a href="controller404">Controller Not found</a></li>
		<li><a href="action404">Action Not found</a></li>
		<li><a href="not-found1">View Not found 1</a></li>
		<li><a href="not-found2">View Not found 2</a></li>
	</ul>

	<h1>Exemplos Avançados</h1>
	<ul>
		<li><a href="send-email">Enviar Email</a></li>
		<li><a href="contato">Contato</a></li>
		<li><a href="uploader">Uploader</a></li>
		<li><a href="pages">ORM - Read</a></li>
		<li><a href="pages/save">ORM - Save</a></li>
		<li><a href="pages/update">ORM - Update</a></li>
	</ul>
</main>