<?php /* @var $this \Win\Mvc\View */ ?>
<main class="page-error">
	<h1>Página não Encontrada</h1>

	<div class="columns">
		<div class="column error">
			<div class='dino'></div>
			<div class='eye'></div>
			<div class='mouth'></div>
			<div class='ground'></div>
			<div class='comets'></div>
		</div>
		<div class="column info-error">
			<strong>404</strong>
			<em>Página Não Encontrada</em>
			<div class="text-center">
				<span>Essa página não existe ou está temporariamente indisponível.</span>
				<span>Verifique se você digitou o endereço corretamente.</span>
				<span>Tente novamente mais tarde ou entre em contato.</span>
				<br />
			</div>

			<div class="text-center buttons">
				<a href="index" class="btn">Ir para à Página Inicial</a>
				<a href="javascript:history.back(-1)" class="btn">Voltar</a>
			</div>
		</div>
	</div>

</main>