<?php /* @var $this Win\Mvc\View */ ?>
<main>
	<h1 class="title-error">ERROR 404</h1>

	<div class="columns">
		<div class="column error">
			<div class='dino'></div>
			<div class='eye'></div>
			<div class='mouth'></div>
			<div class='ground'></div>
			<div class='comets'></div>
		</div>
		<div class="column info-error">
			<strong>404</strong>
			<em>Página Não Encontrada</em>
			<span>Essa página não existe ou está temporariamente indisponível.</span>
			<span>Verifique se você digitou o endereço corretamente.</span>
			<span>Tente novamente mais tarde ou entre em contato.</span>
			
			<div class="buttons">
				<a href="index" class="btn btn-initial">Ir para a Página Inicial</a>
				<a href="javascript:history.back(-1)" class="btn btn-back">Voltar</a>
			</div>
		</div>
	</div>

</main>