<?php /* @var $this \Win\Mvc\View */ ?>
<main>
	<h1>Ops, tivemos um problema!</h1>

	<div class="text-center">
		A Conexão com o o banco de dados não pode ser completada.<br />
		Tente novamente mais tarde ou entre em contato.<br />
		<br />
	</div>

	<div class="text-center buttons">
		<a href="index" class="btn">Ir para à Página Inicial</a>
		<a href="javascript:location.reload()" class="btn">Tentar Novamente</a>
	</div>
</div>

</main>