<?php /* @var $this \Win\Mvc\View */ ?>
<main>
	<h1>Bem-vindo ao <?= $this->app->getName(); ?></h1>

	<div class="row">
		<h2>Título</h2>
		<p>
			<span class="art">
				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur impedit non consectetur vitae unde fugiat temporibus, voluptatibus quaerat dolorum suscipit animi sit itaque magni ipsa necessitatibus, enim, et adipisci nemo voluptate quas tempore dolore iure! Blanditiis cum, porro facilis, inventore impedit debitis. Vero impedit enim dignissimos numquam, id, magni asperiores reiciendis non magnam, quia velit incidunt. Aliquid assumenda doloremque fugiat facilis vero non. Iusto ea dolores ab excepturi, maxime perspiciatis omnis eum provident placeat error deleniti nemo dignissimos qui sunt eaque, accusantium aut inventore sapiente! Distinctio, eos facere, a provident sint facilis, non nemo fuga cum itaque ad! Quia, maiores! <br><br>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur impedit non consectetur vitae unde fugiat temporibus, voluptatibus quaerat dolorum suscipit animi sit itaque magni ipsa necessitatibus, enim, et adipisci nemo voluptate quas tempore dolore iure! Blanditiis cum, porro facilis, inventore impedit debitis. Vero impedit enim dignissimos numquam, id, magni asperiores reiciendis non magnam, quia velit incidunt. Aliquid assumenda doloremque fugiat facilis vero non. Iusto ea dolores ab excepturi, maxime perspiciatis omnis eum provident placeat error deleniti nemo dignissimos qui sunt eaque, accusantium aut inventore sapiente! Distinctio, eos facere, a provident sint facilis, non nemo fuga cum itaque ad! Quia, maiores! Distinctio, eos facere, a provident sint facilis, non nemo fuga cum itaque ad! Quia, maiores!
			</span>
		</p>
	</div>
	<div class="columns">
		<div class="column">
			<h2>Título</h2>
			<p>
				<span class="art">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit aperiam deleniti blanditiis exercitationem cum, nam laboriosam rem et saepe repellat tempore libero sapiente ducimus fugiat. Quibusdam dolore illo ipsam facere. Omnis voluptas illo maxime dolorem nihil nam veritatis blanditiis, iusto ex officiis alias, excepturi neque obcaecati culpa similique et in!</span>
			</p>
		</div>
		<div class="column">
			<h2>Título</h2>
			<p>
				<span class="art">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit aperiam deleniti blanditiis exercitationem cum, nam laboriosam rem et saepe repellat tempore libero sapiente ducimus fugiat. Quibusdam dolore illo ipsam facere. Omnis voluptas illo maxime dolorem nihil nam veritatis blanditiis, iusto ex officiis alias, excepturi neque obcaecati culpa similique et in!</span>
			</p>
		</div>
		<div class="column">
			<h2>Título</h2>
			<p>
				<span class="art">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit aperiam deleniti blanditiis exercitationem cum, nam laboriosam rem et saepe repellat tempore libero sapiente ducimus fugiat. Quibusdam dolore illo ipsam facere. Omnis voluptas illo maxime dolorem nihil nam veritatis blanditiis, iusto ex officiis alias, excepturi neque obcaecati culpa similique et in!</span>
			</p>
		</div>
	</div>

</main>