<?php

use App\Models\Page;
use App\Repositories\PageCategoryRepo;
use Win\Common\Utils\Date;
use Win\Views\View;

/** @var View $this */
/** @var Page $page */
/** @var PageCategoryRepo $categoryRepo */
?>
<main>
	<div class="row">
		<h2>
			<?= $page->title; ?>
		</h2>
		<?php if ($page->createdAt) : ?>
			<b>Criado em: <?= Date::format($page->createdAt, 'd/m/Y H:i:s'); ?></b>
		<?php endif; ?>
		<?php if ($page->categoryId) : ?>
			<br />
			<b>Categoria: <?= $categoryRepo->find($page->categoryId); ?></b>
		<?php endif; ?>
		<p>
			<?= nl2br($page->description); ?>
		</p>
	</div>
</main>