<?php

use App\Models\Page;
use App\Models\PageCategory;
use App\Repositories\PageRepo;
use Win\Blocks\Block;
use Win\Views\View;

/** @var View $this */
/** @var PageCategory[] $categories */
/** @var PageCategory $category */
/** @var Page[] $pages */
/** @var PageRepo $repo */
?>
<main>
	<div class="row">
		<h2>
			Paginas
			<?php if (isset($category)) : ?>
				<?= '-' . $category->title; ?>
			<?php endif; ?>
		</h2>
		<div class="columns">
			<div class="column">
				<b>MENU</b>
				<ul>
					<?php foreach ($categories as $category) : ?>
						<li>
							<a href="pages/<?= $category->id; ?>">
								<?= $category->title; ?>
							</a>
						</li>
					<?php endforeach; ?>
				</ul>
			</div>
			<div class="column column-2">
				<b>PAGES:</b>
				<ul>
					<?php foreach ($pages as $page) : ?>
						<li>
							<a href="page/<?= $page->id; ?>">
								<?= $page->title; ?>
							</a>
						</li>
					<?php endforeach; ?>
				</ul>

				<div style="width: 100%">
					<?= new Block('shared/pagination', get_object_vars($repo->pagination)); ?>
				</div>
			</div>
		</div>
	</div>

	<hr />
	<?= new Block('pages/most-recent'); ?>
</main>