<?php

use Win\Views\View;

/** @var View $this */
?>
<main>
	<h1>Exemplos Básicos</h1>

	<ul>
		<li><a href="database">Database</a></li>
		<li><a href="pages">ORM</a></li>
		<li><a href="alerts">Alert</a></li>
		<li><a href="redirect">Redirecionador</a></li>
		<li><a href="uploader">Uploader</a></li>
	</ul>

	<ul>
		<li><a href="demo">Básico</a></li>
		<li><a href="view-set-values">View Title</a></li>
		<li><a href="namespace">Namespace</a></li>
		<li><a href="json-api">Json API</a></li>
		<li><a href="return-five">Return 5</a></li>
	</ul>
</main>