<?php /* @var $this \Win\Mvc\View */ ?>
<main>
	<h1>Entrar</h1>

	<form method="post">
		<?php Win\Alert\Session::showAlerts(); ?>
		
		<fieldset>
			<input type="text" name="email" value="<?= $this->app->getUser()->getEmail(); ?>" required placeholder="Seu E-mail" />
			<input type="password" name="password" value="" required placeholder="Sua Senha" />
		</fieldset>

		<div class="form-buttons">
			<button type="submit" name="submit" class="btn" value="1">Entrar</button>
		</div>

		<br />
		<div class="text-center">
			<a href="login/recuperar-senha/">Esqueceu a senha?</a>
		</div>
	</form>

</main>