language: php

php:
  - 5.6

before_script:
  - composer install --prefer-dist --dev

script:
  - mkdir -p build/logs
  - phpunit "--bootstrap" "dev/tests/bootstrap.php" "--configuration" "dev/tests/phpunit.xml"
