<?php

use Win\Utils\Str;
use Win\Services\Router;
use Win\Templates\Template;

/** @var Template $this */
$view = $this->app->view;
$title = implode(' | ', (array) ($view->get('title') ?? APP_NAME));
$router = Router::instance();
?>

<head>
	<base href="<?= $router->baseUrl; ?>" />
	<title><?= Str::truncate($title, 150) ?></title>

	<!-- Meta Tags -->
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<!-- Demo Files -->
	<link rel="stylesheet" href="public/css/styles.css" />
	<link rel="shortcut icon" type="image/x-icon" href="public/img/favicon.ico" />

</head>