<?php

use Win\Blocks\Block;
use Win\Common\Pagination;
use Win\Request\Url;

$url = Url::instance()->getUrl();
$showFirst = false;
$showLast = false;

/** @var Block $this */
/** @var Pagination $pagination */
?>
<?php if ($pagination->pageSize() > 0 && $pagination->last() > 0) : ?>
	<ul class="pagination pagination-lg">
		<?php if ($showFirst && $pagination->current() >= 1 + 5) : ?>
			<li>
				<a href="<?= $url; ?>?p=1">
					Primeiro
				</a>
			</li>
		<?php endif; ?>
		<?php if ($pagination->current() > 1) : ?>
			<li>
				<a href="<?= $url; ?>?p=<?= $pagination->prev(); ?>">
					Anterior
				</a>
			</li> <?php endif; ?>
		<?php for ($i = 1; $i <= $pagination->last(); ++$i) : ?>
			<li class="<?= ($i == $pagination->current()) ? 'active' : ''; ?>">
				<a href="<?= $url; ?>?p=<?= $i; ?>">
					<?= $i; ?>
				</a>
			</li>
		<?php endfor; ?>
		<?php if ($pagination->current() < $pagination->last()) : ?>
			<li>
				<a href="<?= $url; ?>?p=<?= $pagination->next(); ?>">
					Próximo
				</a>
			</li>
		<?php endif; ?>
		<?php if ($showLast && $pagination->current() <= $pagination->last() - 5) : ?>
			<li>
				<a href="<?= $url; ?>?p=<?= $pagination->last(); ?>">Último</a>
			</li>
		<?php endif; ?>
	</ul>
<?php endif;
