<?php

use Win\Blocks\Block;
use Win\Common\Pagination;
use Win\Request\Url;

$url = Url::instance()->getUrl();

/** @var Block $this */
/** @var Pagination $pagination */
extract(get_object_vars($pagination));
?>
<?php if ($pageSize > 0 && $last > 0) : ?>
	<ul class="pagination pagination-lg">
		<?php if ($current > 5) : ?>
			<!-- <li class="first">
				<a href="<?= $url; ?>?p=1">
					Primeiro
				</a>
			</li> -->
		<?php endif; ?>
		<?php if ($current > 1) : ?>
			<li class="prev">
				<a href="<?= $url; ?>?p=<?= $prev; ?>">
					Anterior
				</a>
			</li> <?php endif; ?>
		<?php for ($i = 1; $i <= $last; ++$i) : ?>
			<li class="<?= ($i == $current) ? 'active' : ''; ?>">
				<a href="<?= $url; ?>?p=<?= $i; ?>">
					<?= $i; ?>
				</a>
			</li>
		<?php endfor; ?>
		<?php if ($current < $last) : ?>
			<li class="next">
				<a href="<?= $url; ?>?p=<?= $next; ?>">
					Próximo
				</a>
			</li>
		<?php endif; ?>
		<?php if ($current <= $last - 5) : ?>
			<!-- <li class="last">
				<a href="<?= $url; ?>?p=<?= $last; ?>">Último</a>
			</li> -->
		<?php endif; ?>
	</ul>
<?php endif;
