<?php

use Win\Templates\Template;
use Win\Request\Url;

/**
 * @var Template $this
 * @var int $pageSize
 * @var int $last
 * @var int $current
 * @var int $count
 */

$url = Url::$full;
?>
<?php if ($pageSize > 0 && $last > 0) : ?>
	<ul class="pagination pagination-lg">
		<?php if ($current > 5) : ?>
			<!-- <li class="first">
				<a href="<?= $url; ?>?p=1">
					Primeiro
				</a>
			</li> -->
		<?php endif; ?>
		<?php if ($current > 1) : ?>
			<li class="prev">
				<a href="<?= $url; ?>?p=<?= $current - 1; ?>">
					Anterior
				</a>
			</li> <?php endif; ?>
		<?php for ($i = 1; $i <= $last; ++$i) : ?>
			<li class="<?= ($i == $current) ? 'active' : ''; ?>">
				<a href="<?= $url; ?>?p=<?= $i; ?>">
					<?= $i; ?>
				</a>
			</li>
		<?php endfor; ?>
		<?php if ($current < $last) : ?>
			<li class="next">
				<a href="<?= $url; ?>?p=<?= $current + 1; ?>">
					Próximo
				</a>
			</li>
		<?php endif; ?>
		<?php if ($current <= $last - 5) : ?>
			<!-- <li class="last">
				<a href="<?= $url; ?>?p=<?= $last; ?>">Último</a>
			</li> -->
		<?php endif; ?>
	</ul>
<?php endif;
