<?php

use App\Models\Category;
use App\Models\Page;
use App\Repositories\PageOrm;
use Win\Blocks\Block;
use Win\Views\View;

/** @var View $this */
/** @var Category[] $categories */
/** @var Category $category */
/** @var Page[] $pages */
/** @var PageOrm $orm */
?>
<main>
	<div class="row">
		<h2>
			Paginas
			<?php if (isset($category)) : ?>
				<?= '-' . $category->title; ?>
			<?php endif; ?>
		</h2>
		<div class="columns">
			<div class="column">
				<b>MENU</b>
				<ul>
					<?php foreach ($categories as $category) : ?>
						<li>
							<a href="pages/<?= $category->id; ?>">
								<?= $category->title; ?>
							</a>
						</li>
					<?php endforeach; ?>
				</ul>
			</div>
			<div class="column" style="float: left;">
				<b>PAGES:</b>
				<ul>
					<?php foreach ($pages as $page) : ?>
						<li>
							<a href="page/<?= $page->id; ?>">
								<?= $page->title; ?>
							</a>
						</li>
					<?php endforeach; ?>
				</ul>

				<div style="width: 100%">
					<?= (new Block('shared/pagination', ['pagination' => $orm->pagination]))->toHtml(); ?>
				</div>
			</div>
		</div>
	</div>
</main>