<?php

use Win\File\Type\Image;
use Win\Mvc\View;

/* @var $this View */
/* @var $image Image */
?>
<main>
	<h1>Uploader</h1>

	<form method="post" enctype="multipart/form-data">
		<?php if ($image && $image->exists()): ?>
			<img src="<?= $image; ?>" width="<?= $image->getWidth(); ?>" height="<?= $image->getHeight(); ?>" />
		<?php endif; ?>

		<input type="file" name="upload" />
		<input type="submit" name="submit" value="Enviar arquivo" />
	</form>

</main>