<?php /* @var $this Win\Mvc\Block */ ?>
<b>Contato efetuado pelo site <?= $this->app->getName(); ?>: <?= $this->app->getBaseUrl(); ?></b><br />
<br />
<b>Nome:</b> <?= $name ?><br />
<b>Telefone:</b> <?= $phone ?><br />
<b>E-mail:</b> <?= $email ?><br />
<b>Assunto:</b> <?= $subject ?><br />
<b>Mensagem:</b> <?= nl2br($message); ?><br />

<div style="font-size:12px; line-height: 15px; border-top: solid 1px #AAA; margin-top: 10px; padding-top: 10px;">
	<b>IP:</b> <?= $_SERVER['REMOTE_ADDR'] ?><br />
	<b>Host:</b> <?= gethostbyaddr($_SERVER['REMOTE_ADDR']) ?><br />
	<b>Navegador:</b> <?= $_SERVER['HTTP_USER_AGENT'] ?><br />
</div>