<?php

use Win\File\File\Image;
use Win\Html\Form\Select;
use Win\Mvc\View;

/* @var $this View */
/* @var $image Image */
?>
<main>
	<h1>Uploader</h1>

	<form method="post" enctype="multipart/form-data">

		<select>
			<?=  (new Select('animal', ['spaniel' => 'Spaniel', 'luke' => 'Luke']))->htmlContent(); ?>
		</select>


		<?php if ($image && $image->exists()): ?>
			name: <?= $image->getBaseName(); ?><br/>
			width: <?= $image->getWidth(); ?><br/>
			height: <?= $image->getHeight(); ?><br/>
			size: <?= $image->getSize(); ?><br/>

			<div style="max-width: 300px; text-align: center;">
				<img class="thumbnail" src="<?= $image; ?>" style="max-width: 100%;" />
			</div>
		<?php endif; ?>

		<input type="file" name="upload" />
		<input type="submit" name="submit" value="Enviar arquivo" />
	</form>

</main>