<?php

use Win\Blocks\Block;
use Win\Request\Url;

/** @var Block $this */
?>
<head>
	<base href="<?= Url::$base; ?>" />
	<title>
		<?= $this->app->view->getData('title'); ?>
	</title>

	<!-- Meta Tags -->
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<!-- Demo Files -->
	<link rel="stylesheet" href="public/css/styles.css" />
	<link rel="shortcut icon" type="image/x-icon" href="public/img/favicon.ico" />

</head>