<?php
/* @var $this Win\Mvc\Block */
/* @var $email Win\Mailer\Email */
?>

<div id="email-container" style="width:100%; max-width: 500px; margin: 0 auto; border: solid 1px #AAA; border-radius: 3px; font-family: Arial; font-size: 14px; line-height: 16px;">
	<div id="email-header" style="background:#019875; color:#FFF; margin: 5px; text-align: center ">
		<img src="<?= $this->app->getBaseUrl(); ?>public/img/logo.png" alt="logo" style="max-width: 120px; max-height: 60px; margin: 10px auto; border-radius: 3px;" />
	</div>

	<div id="email-content" style="margin:15px; line-height: 22px;">
		<?= $email->getContent(); ?>
	</div>

	<div id="email-footer" style="background:#aaa; color:#FFF; margin: 5px; padding: 10px; font-size:11px;">
		Enviado por:
		<a target="_blank" href="<?= $this->app->getBaseUrl(); ?>" style="color:#EEE" >
			<?= $this->app->getName(); ?>
		</a><br />
		Enviado em: <?= date('d/m/Y') ?> às <?= date('H:i:s') ?><br />
	</div>
</div>