<?php

use App\Templates\ClassView;

/** @var ClassView $this */
?>
<main class="text-center">
	<h1>
		<?= $this->text; ?>
	</h1>

	My code should be 10 = <b><?= $this->code; ?> = <?= $this->getCode(); ?></b>
	<br /> <br />
	Acessa variável private:
	<?= isset($this->varPrivate) ? 'SIM' : 'NÃO'; ?>
	<br />
	Acessa variável protected:
	<?= isset($this->code) ? 'SIM' : 'NÃO'; ?>

	<br><br>
	<a class="btn" href="./">Voltar à Página Inicial</a>
</main>